---
name: Test, Build, and Push
on:
  push:
    branches:
      - master

jobs:
  gotest:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - run: go mod download
      - run: go test -race -v ./

  build-push:
    name: Build & Push
    needs: [ "gotest" ]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - uses: actions/checkout@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: zostay/ext-authz-keep-out:latest
